# Generated by Django 5.0.3 on 2024-04-24 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('famTree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyNode',
            fields=[
                ('id', models.JSONField(primary_key=True, serialize=False, unique=True)),
                ('fid', models.JSONField(default=None, null=True)),
                ('mid', models.JSONField(default=None, null=True)),
                ('pids', models.JSONField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(default=None, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='famTree/')),
                ('phone', models.IntegerField(default=0, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(default='2002-09-20', null=True)),
                ('days_until_birthday', models.IntegerField(blank=True, null=True)),
                ('relationship', models.CharField(max_length=20, null=True)),
                ('total_members', models.IntegerField(default=0, null=True)),
                ('total_male', models.IntegerField(default=0, null=True)),
                ('total_female', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='famTree.familynode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='famTree.familynode')),
            ],
        ),
    ]
