# Generated by Django 5.0.3 on 2024-05-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famTree', '0003_auto_20240424_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='familynode',
            name='special_event',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
