# Generated by Django 5.0.3 on 2024-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famTree', '0004_familynode_special_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='familynode',
            name='other_comments',
            field=models.TextField(default=None, null=True),
        ),
    ]
